server.port=8084
spring.application.name=RecuritPortal
spring.mvc.view.prefix=/webpages/
spring.mvc.view.suffix=.jsp
#spring.datasource.url=jdbc:h2:file:./resources/data/recurit_db
#spring.datasource.url=jdbc:h2:file:./src/main/resources/data/recurit_db;AUTO_SERVER=TRUE
spring.datasource.url=jdbc:h2:./target/classes/data/recurit_db;AUTO_SERVER=TRUE
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.h2.console.enabled=true
spring.sql.init.platform=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=